"""add verified_email and two_factor_code to user

Revision ID: 1219d4c0052e
Revises: 9b912025f007
Create Date: 2024-08-10 12:08:44.454511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1219d4c0052e'
down_revision = '9b912025f007'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verified_email', sa.Boolean(), server_default=sa.text('false'), nullable=False))
        batch_op.add_column(sa.Column('two_factor_code', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('two_factor_code')
        batch_op.drop_column('verified_email')

    # ### end Alembic commands ###
