"""add communities

Revision ID: 5d4fea096797
Revises: 5d9d2e07454e
Create Date: 2024-06-06 01:07:51.356487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d4fea096797'
down_revision = '5d9d2e07454e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('community',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('register_date', sa.DateTime(), nullable=False),
    sa.Column('image_url', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('community', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_community_register_date'), ['register_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_user_id'), ['user_id'], unique=False)

    op.create_table('community_user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('join_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['community.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('user_id', 'community_id')
    )
    with op.batch_alter_table('community_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_community_user_join_date'), ['join_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_community_user_join_date'))

    op.drop_table('community_user')
    with op.batch_alter_table('community', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_community_user_id'))
        batch_op.drop_index(batch_op.f('ix_community_register_date'))

    op.drop_table('community')
    # ### end Alembic commands ###
