"""add community name

Revision ID: 5dbe6f3ebb60
Revises: adf240b4bd42
Create Date: 2024-06-06 19:21:47.234258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dbe6f3ebb60'
down_revision = 'adf240b4bd42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=32), nullable=False))
        batch_op.create_index(batch_op.f('ix_community_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_community_name'))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
