"""add vacancies

Revision ID: 7a7f526fde97
Revises: 67609222f411
Create Date: 2024-06-13 14:27:15.841749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a7f526fde97'
down_revision = '67609222f411'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vacancy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vacancy', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vacancy_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_vacancy_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vacancy', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vacancy_user_id'))
        batch_op.drop_index(batch_op.f('ix_vacancy_date'))

    op.drop_table('vacancy')
    # ### end Alembic commands ###
