"""add skills

Revision ID: 9b912025f007
Revises: 7a7f526fde97
Create Date: 2024-06-15 03:42:12.949476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b912025f007'
down_revision = '7a7f526fde97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skills', sa.String(length=100), nullable=True))

    with op.batch_alter_table('vacancy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skills', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vacancy', schema=None) as batch_op:
        batch_op.drop_column('skills')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('skills')

    # ### end Alembic commands ###
